### ISSUE TITLE
Can not works in Fabric 1.20.1 without Sodium

### ISSUE THREAD

**Issue by luyr-clavia** [FxMorin/MoreCulling#388]
Minecraft can't launch with MoreCulling *clean installation*.

https://mclo.gs/XOk8a1a

```
net.minecraft.class_148: Rendering overlay
	at net.minecraft.class_757.method_3192(class_757.java:941) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.14.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/client/indigo/renderer/mesh/EncodingFormat
	at ca.fxco.moreculling.utils.VertexUtils.getPos(VertexUtils.java:40) ~[moreculling-1.20.4-0.24.0.jar:?]
	at ca.fxco.moreculling.utils.VertexUtils.getQuadBounds(VertexUtils.java:59) ~[moreculling-1.20.4-0.24.0.jar:?]
	at net.minecraft.class_1093.resetTranslucencyCache(class_1093.java:554) ~[client-intermediary.jar:?]
	at net.minecraft.class_1093.handler$zzl000$moreculling$onInit(class_1093.java:594) ~[client-intermediary.jar:?]
	at net.minecraft.class_1093.<init>(class_1093.java:37) ~[client-intermediary.jar:?]
	at net.minecraft.class_1093$class_1094.method_4746(class_1093.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_793.method_3446(class_793.java:228) ~[client-intermediary.jar:?]
	at net.minecraft.class_793.method_4753(class_793.java:203) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088$class_7778.method_45873(class_1088.java:426) ~[client-intermediary.jar:?]
	at net.minecraft.class_807.method_4753(class_807.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_816.method_4753(class_816.java:89) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088$class_7778.method_45873(class_1088.java:426) ~[client-intermediary.jar:?]
	at net.minecraft.class_1088.method_45877(class_1088.java:188) ~[client-intermediary.jar:?]
	at java.util.HashMap$KeySet.forEach(HashMap.java:1008) ~[?:?]
	at net.minecraft.class_1088.method_45876(class_1088.java:185) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_45883(class_1092.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_1092.method_45885(class_1092.java:92) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```
